use serde_json::{json, Value};
use tauri::State;

use crate::db::DbState;

/// Embedded bundle manifest — generated by export-bundles.py
const BUNDLE_MANIFEST: &str = include_str!("../../../data/bundles/manifest.json");

#[tauri::command]
pub fn list_bundles(db: State<DbState>) -> Result<Value, String> {
    let manifest: Value = serde_json::from_str(BUNDLE_MANIFEST).map_err(|e| e.to_string())?;

    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    // Get installed volume stats
    let mut stmt = conn
        .prepare(
            "SELECT v.id, v.abbreviation, COUNT(vs.id) as verse_count
             FROM volumes v
             LEFT JOIN verses vs ON vs.volume_id = v.id
             GROUP BY v.id",
        )
        .map_err(|e| e.to_string())?;

    let installed: Vec<(i64, String, i64)> = stmt
        .query_map([], |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, i64>(2)?,
            ))
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    let installed_map: std::collections::HashMap<String, i64> = installed
        .into_iter()
        .map(|(_, abbr, count)| (abbr, count))
        .collect();

    // Check hymns
    let hymn_count: i64 = conn
        .query_row("SELECT COUNT(*) FROM hymns", [], |row| row.get(0))
        .unwrap_or(0);

    // Enrich manifest bundles with installed status
    let bundles = manifest["bundles"].as_array().cloned().unwrap_or_default();

    let enriched: Vec<Value> = bundles
        .into_iter()
        .map(|mut b| {
            let id = b["id"].as_str().unwrap_or("");
            let (installed, installed_count) = if id == "hymns" {
                (hymn_count > 0, hymn_count)
            } else {
                let count = installed_map.get(id).copied().unwrap_or(0);
                (count > 0, count)
            };
            b["installed"] = json!(installed);
            b["installed_verse_count"] = json!(installed_count);
            b
        })
        .collect();

    Ok(json!({
        "version": manifest["version"],
        "bundles": enriched
    }))
}
